### ISSUE TITLE
Repository creation fails with Spring boot 1.5.1 + 

### ISSUE THREAD

**Issue by dturanski** [spring-projects/spring-data-geode#2]
This happens with `1.0.0.INCUBATING-RELEASE`

Googling around I found this similar issue https://github.com/darrachequesne/spring-data-jpa-datatables/issues/50

See [my demo app](https://github.com/dturanski/SpringBootPccDemo). You can run it against a local server and create region --name employee --type REPLICATE. Switch to boot 1.5.1.RELEASE or later to reproduce the issue.

**Comment by jxblum** [comment]
Hi @dturanski -

_Spring Boot_ `1.5.1.RELEASE` is [using](https://github.com/spring-projects/spring-boot/blob/v1.5.1.RELEASE/spring-boot-dependencies/pom.xml#L157) SD `Ingalls-RELEASE`.

_Spring Data_ **_Ingalls_** is [based](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Ingalls#spring-data-commons---113) on _Spring Data Commons_ `1.13`.

_Spring Data Commons_ [moved to "constructor injection"](https://github.com/spring-projects/spring-data-commons/commit/259a1e0958fd84b95ab4e779475bcf005ba055a6) to [set the application _Repository_ interface](https://github.com/spring-projects/spring-data-commons/blob/1.13.0.RC1/src/main/java/org/springframework/data/repository/core/support/RepositoryFactoryBeanSupport.java#L73-L82), [replacing the setter](https://github.com/spring-projects/spring-data-commons/blob/1.13.0.M1/src/main/java/org/springframework/data/repository/core/support/RepositoryFactoryBeanSupport.java#L70-L80).

_Spring Data Geode_ `1.0.0.INCUBATING-RELEASE` predates this change as SD Geode was [based on](https://github.com/spring-projects/spring-data-gemfire/blob/1.0.0.APACHE-GEODE-INCUBATING-RELEASE/gradle.properties#L21) _Spring Data Commons_ `1.12.5.RELEASE`, which did not have this change (i.e. SDC `1.12.5.RELEASE` was still [based on the setter](https://github.com/spring-projects/spring-data-commons/blob/1.12.5.RELEASE/src/main/java/org/springframework/data/repository/core/support/RepositoryFactoryBeanSupport.java#L70-L80)).

Due to security issues in both _Apache Geode_ `1.0.x` & `1.1.x` line, there will be no more releases of SD Geode 1.0.x or any 1.1.x release, which are based on _Apache Geode_ `1.0.x` and `1.1.x`, respectively.  The _Apache Geode_ community does **not** release patches for past versions.  They just push forward with subsequent releases 1.2, 1.3, etc.

_Spring Data Geode_ **2.0** is joining the SD **_Kay_** _Release Train_ and will be based on Spring _Framework_ `5.0`, _Spring Data Commons_ `2.0`, _Spring Boot_ `2.0`, etc, and will have this change.

At this point, everything is pointing to the future and it is unlikely that I will release a SD Geode 1.1.x version based on _Spring Boot_ `1.5.x` given current priorities.

**Comment by jxblum** [comment]
I will leave this open for the time being, but I am not likely to do anything about this.

NOTE: _Spring Data GemFire_ **_Ingalls_** does work with _Spring Boot_ `1.5.1.RELEASE` and later.

**Comment by dturanski** [comment]
Thanks John. Sounds like for Boot + SDG + PCC it's either boot 1.4.x or boot 2.0

**Comment by jxblum** [comment]
Right, for _Spring Data Geode_ anyway.  _Spring Data GemFire_ **1.9.x** (_Ingalls_) will work with _Spring Boot_ **1.5.x**.
