### ISSUE TITLE
Add support to manage a cache server with Gfsh

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-projects/spring-data-geode#3]
It'd be great if a gfsh "stop server" command could also shutdown the hosting spring-boot process when using spring-data-geode. I understand that this is not something we'd want to have as a default behavior but it can be convenient. 

Perusing through the code, I was unable to find a way to accomplish this. Is this possible with the current APIs?

**Comment by jxblum** [comment]
> _Perusing through the code, I was unable to find a way to accomplish this. Is this possible with the current APIs?_

The short answer is, it is **not** easily feasible, or really possible.

The long answer is rather involved and encompasses with the way in which Apache Geode's, Geode Shell tool (_Gfsh_) launches and manages its servers, which is not "aware" of other potential existing services.

Under-the-hood, _Gfsh's_ `stop server` command is based on the [`o.a.g.distributed.ServerLauncher`](http://geode.apache.org/releases/latest/javadoc/org/apache/geode/distributed/ServerLauncher.html) class.  Internally, Apache Geode's Management infrastructure, which is JMX-based, creates Java registers Java MBeans with the JRE process's PlatformMBeanServer along with an internal, hidden Apache Geode Region to federate the data and management of servers across the cluster.  The MBeans that start and stop (or sometimes pause/resume) GemFire processes or services use other classes to ascertain the state of the processes, or servers.  In the `stop server` command's case, it relies on state derived from an instance of the `o.a.g.distributed.ServerLauncher` class, which _Gfsh_ used to launch the server with `start server`.

Since a _Spring Boot_ application possibly "embeds" a Geode (cache) server process in the "_Spring Boot_" JVM (first), a Geode server in this case would not be launched using an instance of the `o.a.g.distributed.ServerLauncher` class.  Plus, `o.a.g.distributed.ServerLauncher` is pretty specific to the way Gfsh and Geode's Management infrastructure functions, therefore, has not direct utility in SDG.

You should also keep in mind that the _Spring_ container is the one thing bootstrapping all the services that your application requires to run.  _Spring Boot_ starts by configuring and initializing the _Spring_ container.  _Spring_ and _Spring Boot_ may in turn bootstrap/run an "embedded" Tomcat/Jetty HTTP server instance, particularly if your application is a Web application (that is, you have `spring-boot-starter-web` on the classpath).  You might be running an "embedded" Message Bus or be interfacing with an "embedded" database (e.g. HSQL or H2, etc) in an application.  All of these services much be properly shutdown when your _Spring Boot_ application is shutdown.

Having _Gfsh_ stop the _Spring Boot_ application just because it has embedded an instance of Apache Geode is a bit shortsighted in the scenario above, which is not at all uncommon.  Additionally, Gfsh is not going to be aware of the _Spring_ container in your application, much less these other services.  Furthermore, it is much more common that your Spring Boot application is an Apache Geode `ClientCache` (or cache client) application than an actual "peer" `Cache` application, that is a member and part of the cluster of servers.

Having said this, it is possible to run `describe member` (and most other Gfsh commands, minus the lifecycle commands (i.e. `start`, `stop`, `status`)) on a _Spring Boot_, Apache Geode-based Server application.  I have examples along with documentation for this [here](https://github.com/jxblum/spring-boot-gemfire-server-example) and [here](https://github.com/jxblum/pivotal-gemfire-clientserver-examples) even

Now, on the flip-side, it is possible to start an Apache Geode server with Gfsh bootstrapped with Spring by using "`start server --name=SpringConfigureGeodeServer --spring-xml-location=/classpath/to/spring/application/context.xml --classpath=/absolute/file/system/path/to/spring-data-geode-2.0.3.RELEASE.jar:...`".

In this case, the JVM process is an Apache Geode server first, which then bootstraps a _Spring_ container that then can initialize the Geode server (i.e. `Cache` and `CacheServer` instances) started in _Gfsh_.  You only need to ensure that SDG is on your server's classpath when starting the server in _Gfsh_ in this way.  When the server is bootstrapped and configured/initialized with _Spring_ in this manner, it is then possible to control the server status (i.e. `status server`) and shutdown (using `stop server`) in _Gfsh_.  However, it will no longer be a _Spring Boot_ application.

See the corresponding SDG docs for [more details](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#gemfire-bootstrap).

**Comment by PedroAlvarado** [comment]
Thanks John. I understand. That said, it is important that we highlight in the SDG documentation, in a way akin to `@EnableLocator` and `@EnableManager`, that currently the usage of the `@CacheServerApplication` and `@PeerCacheApplication` annotations is not a recommended way to add members to a server cluster in production environments. Similarly, the documentation should stress that SDG, under a Client/Server topology and in a production environment, should be used as client only. For a novice user, this may be something that can be easily missed. Let me know if this make sense to you.

Moreover, I'll take the liberty to add here some of the consequences of adding a member to a server cluster in a production environment using `@CacheServerApplication` and `@PeerCacheApplication`.

*There are two lifecycles at play to be managed: the spring-boot app and the embedded geode server
*Per above, no complete GFSH support for server lifecycle management is available.
*Per above, member instrumentation requires a combination of GFSH and custom code(e.g stop/start server scripts, spring-boot health indicators, etc)
*Member default configuration may be different than documented Geode configuration defaults. (e.g. disable-auto-reconnect is set to false in vanilla Geode however in SDG its practically true)

**Comment by jxblum** [comment]
Hi Pedro,

Yes, very valid points.  I can definitely see how `@EnableLocator` and `@EnableManager` combined with the starting Annotations, either `@PeerCacheApplication` or `@CacheServerApplication`, would lead users to think that using these configuration options is the "recommended" way to starting servers, and more importantly, managing servers.

I have, fairly recently in fact, taken a very client centric approach for SDG.  This has to do, in no small part, with Pivotal Cloud Foundry.  When using PCF, the application developer really does not need to worry about the cluster of servers, other than managing and monitoring.  Provisioning is handled by the CF platform.

Having said that, I would say it also depends.

In fact, some users/customers do actually start and manage their clusters with _Spring Boot_, or more generally, with a _Spring_-first approach, while other users/customers have strict requirements from their administrative ops teams that impose on developers that they must use the tools provided with their database backends.  For Apache Geode, or more specifically, Pivotal GemFire, that usually means developers and ops teams must use _Gfsh_ and Pulse, despite both tools not being entirely complete or all inclusive...

Unfortunately, even though the _Spring_ team makes a best effort to provide interoperability and a seamless experience, it is not always reciprocal.  That is the Apache Geode community does not always do things that are in the best interests of the extended community, e.g. making things work in other contexts, like a _Spring_ context.  In many cases, I have really gone to great lengths in order to make Apache Geode play nice in a _Spring_ context.  But sometimes, I just need certain support from Apache Geode to do certain things.

Anyway, it is no excuse for clear documentation along with examples, and by no means, are either complete.  I definitely appreciate your feedback.

Now, to quickly address some of your other points.  Regarding...

> * There are two lifecycles at play to be managed: the spring-boot app and the embedded geode server

So, when _Spring_ is doing the "bootstrapping" (i.e. you are using an embedded approach, which is perfectly valid), then you can rest assured that _Spring (Data Geode)_ will do the right thing to manage the Apache Geode lifecycle in a _Spring_ context.

As you know, _Spring_ provides many [lifecycle hooks (callbacks)](https://docs.spring.io/spring/docs/5.0.2.RELEASE/spring-framework-reference/core.html#beans-factory-nature) to ensure that external services, like Apache Geode, are managed appropriately in a _Spring_ context.

**Comment by jxblum** [comment]
Closing as "_won't-fix_".  This Issue will morph into providing more complete documentation and examples instead.
