### ISSUE TITLE
<gfe:entry-ttl> and <gfe:entry-tti>elements are not allowed under <gfe:replicated-region>

### ISSUE THREAD

**Issue by sjoshid** [spring-projects/spring-data-geode#616]
Im using Apache Geode 1.14.4 and spring-data-geode version 2.7.2. 
I have following region config which fails to bring up my app. 

```
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:gfe="http://www.springframework.org/schema/geode"
       xsi:schemaLocation="http://www.springframework.org/schema/geode http://www.springframework.org/schema/geode/spring-geode.xsd">
    <gfe:replicated-region id="regionId" cache-ref="myCacheRef">
        <!-- When region.get(k) is a cache-miss, this loader will be called to load the value (eg. from db) -->
        <gfe:cache-loader ref="myLoader"/>
        <gfe:cache-writer ref="myWriter"/>
        <!-- Time-to-live (TTL) is used for creation and put operations -->
        <gfe:entry-ttl timeout="300" action="DESTROY"/>
        <!-- Idle timeout (TTI) is used for get and netSearch operations -->
        <gfe:entry-tti timeout="300" action="DESTROY"/>
    </gfe:replicated-region>
</beans>
```

The exact error is:
`org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 29 in XML document from file [C:\Users\sjoshi\context\geode-context.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 29; columnNumber: 56; cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.springframework.org/schema/geode":entry-ttl}'. One of '{"http://www.springframework.org/schema/geode":membership-attributes, "http://www.springframework.org/schema/geode":gateway-sender, "http://www.springframework.org/schema/geode":gateway-sender-ref, "http://www.springframework.org/schema/geode":async-event-queue, "http://www.springframework.org/schema/geode":async-event-queue-ref, "http://www.springframework.org/schema/geode":subscription, "http://www.springframework.org/schema/geode":eviction, "http://www.springframework.org/schema/geode":lookup-region, "http://www.springframework.org/schema/geode":replicated-region, "http://www.springframework.org/schema/geode":partitioned-region, "http://www.springframework.org/schema/geode":local-region, "http://www.springframework.org/schema/geode":client-region}' is expected.`

**Comment by jxblum** [comment]
Your SDG XML configuration metadata (above) is not correctly defined (formed) according to the SDG XSD (see [here](https://www.springframework.org/schema/geode/spring-geode.xsd)).

Specifically, the ordering of the `CacheLoader/Writer` configuration elements (i.e. `<gfe:cache-loader>` and `<gfe:cache-writer>`) inside the Replicated Region element is not correct.

It should be defined as:

```xml
<beans xmlns="http://www.springframework.org/schema/beans"
              xmlns:gfe="http://www.springframework.org/schema/geode"
              xsi:schemaLocation="http://www.springframework.org/schema/geode 
                  http://www.springframework.org/schema/geode/spring-geode.xsd">

    <gfe:replicated-region id="regionId" cache-ref="myCacheRef">
        <gfe:entry-ttl timeout="300" action="DESTROY"/>
        <gfe:entry-tti timeout="300" action="DESTROY"/>
        <gfe:cache-loader ref="myLoader"/>
        <gfe:cache-writer ref="myWriter"/>
    </gfe:replicated-region>
</beans>
```

**Comment by sjoshid** [comment]
I had no clue entries need to be ordered 🤯

**Comment by jxblum** [comment]
I was able to reproduce your outcome using the SDG `RegionExpirationAttributesNamespaceIntegrationTests` class (see [here](https://github.com/spring-projects/spring-data-geode/blob/2.7.x/spring-data-geode/src/test/java/org/springframework/data/gemfire/config/xml/RegionExpirationAttributesNamespaceIntegrationTests.java)) with its associated XML configuration file (see [here](https://github.com/spring-projects/spring-data-geode/blob/2.7.x/spring-data-geode/src/test/resources/org/springframework/data/gemfire/config/xml/RegionExpirationAttributesNamespaceIntegrationTests-context.xml)). You can see the changes that I made in this [commit](https://github.com/spring-projects/spring-data-geode/commit/b2cf973a52d2bdc064971dbfe6d759fe8bffa80c).

Specifically, I defined `CacheListener`, `CacheLoader` and `CacheWriter` configuration elements for the Replicated Region,
[here](https://github.com/spring-projects/spring-data-geode/blob/2.7.x/spring-data-geode/src/test/resources/org/springframework/data/gemfire/config/xml/RegionExpirationAttributesNamespaceIntegrationTests-context.xml#L32-L38). This works as expected and the test passes!

**Comment by jxblum** [comment]
In general, the ordering of elements defined by the SDG XSD has existed for as long as SD Geode has been project. While some of the restrictions defined in the SDG XSD may be possible to lift, changing the XSD even a slight bit, could potentially and adversely affect other users's existing configuration metadata.

So, we don't generally make many changes to the XSD, such as re-ordering of the elements, changing type definitions, or otherwise, in any significant way.

Also, among many others reasons, this is also 1 reason why Spring overall has gravitated away from XML configuration metadata in favor of _JavaConfig_.

SDG has comprehensive support for Annotation-based (see [here](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config)) as well as Java-based configuration metadata (see the [API](https://docs.spring.io/spring-data/geode/docs/current/api/)).

On top of that _**Spring Boot for Apache Geode**_ (SBDG) makes this even easier with Spring Boot's auto-configuration, convention over configuration approach. See project page [here](https://github.com/spring-projects/spring-boot-data-geode#spring-boot-for-apache-geode), and documentation [here](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/) (Ref Doc) and [here](https://docs.spring.io/spring-boot-data-geode-build/current/api/) (_Javadoc_).

A really good way to get started is by looking at the [Samples](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-samples), and specifically, the [Getting Started](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/guides/getting-started.html) sample.

_Spring Boot_ is the way.

I recommend moving away from XML configuration.

**Comment by sjoshid** [comment]
Any reason why the ordering matters here? It is so unexpected.

**Comment by sjoshid** [comment]
That all makes sense. I honestly didnt even know ordering can be mandated by an xsd like that. 
I would like to switch to Spring Boot. One day...
